<?php

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;
$mydirname="";
$mydirname = basename( dirname( __FILE__ ) ) ;
$GLOBALS["MRBS_PREFIX"] = strtoupper($mydirname);
if ( !file_exists(XOOPS_ROOT_PATH.'/modules/'.$mydirname.'/sql/'.$mydirname.'.sql')) {

    if( ! preg_match( '/^(\D+)(\d*)$/' , $mydirname , $regs ) ) {echo ( "invalid dirname: " . htmlspecialchars( $mydirname ) ) ;}

    $modulefolder = '';
    include_once XOOPS_ROOT_PATH.'/modules/'.$mydirname.'/sql/mysql.php';
    $fp = fopen(XOOPS_ROOT_PATH.'/modules/'.$mydirname.'/sql/'.$mydirname.'.sql','w');
    $content = $modulefolder;
    $search_pattern = array('%modulename%');
    $replace_pattern = array($mydirname);
    $content = str_replace($search_pattern, $replace_pattern, $content);
    fwrite($fp, $content);
    fclose($fp);
} //end if -  $mydirname.sql file
//$modversion['name'] = "mrbs";
$modversion['name'] = $mydirname ;
$modversion['version'] = 1.48;
$modversion['description'] = "Meeting room booking system";
$modversion['author'] = 'jobrazo';
$modversion['nickname'] = 'jobrazo';

$modversion['credits'] = "From http://mrbs.sourceforge.net";
//$modversion['help'] = "MRBS version 1.4.8";
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = "images/mrbs.png";

//$modversion['dirname'] = "mrbs";
$modversion['dirname'] = $mydirname ;

$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion['release_date']     = '2012/01/16';
$modversion["module_website_url"] = "http://www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["module_status"] = "Beta";
$modversion["author_website_url"] = "http://mrbs.sourceforge.net/";
$modversion["author_website_name"] = "MRSB";
$modversion['min_php']='5.2';
$modversion['min_xoops']="2.5";
$modversion['min_admin']='1.1';
$modversion['min_db']= array('mysql'=>'5.0.7', 'mysqli'=>'5.0.7');

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/".$mydirname.".sql";


//cloon change start
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = $mydirname."_area";
$modversion['tables'][1] = $mydirname."_entry";
$modversion['tables'][2] = $mydirname."_repeat";
$modversion['tables'][3] = $mydirname."_room";
//cloon change end

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Blocks

// Menu
$modversion['hasMain'] = 1;

// Search
$modversion['hasSearch'] = 0;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "mrbs_search";

// Comments
$modversion['hasComment'] = 0;

$modversion['config'][0]['name'] = 'mrbs_admin';
$modversion['config'][0]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_ADMIN';
$modversion['config'][0]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_ADMIN_DESC';
$modversion['config'][0]['formtype'] = 'textbox';
$modversion['config'][0]['valuetype'] = 'text';
$modversion['config'][0]['default'] = "Admin name";

$modversion['config'][1]['name'] = 'mrbs_admin_email';
$modversion['config'][1]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_ADMIN_EMAIL';
$modversion['config'][1]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_ADMIN_EMAIL_DESC';
$modversion['config'][1]['formtype'] = 'textbox';
$modversion['config'][1]['valuetype'] = 'text';
$modversion['config'][1]['default'] = "admin@email.here";

$modversion['config'][2]['name'] = 'mrbs_company';
$modversion['config'][2]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY';
$modversion['config'][2]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY_DESC';
$modversion['config'][2]['formtype'] = 'textbox';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = "Your company";

$modversion['config'][3]['name'] = 'mrbs_company_logo';
$modversion['config'][3]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY_LOGO';
$modversion['config'][3]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY_LOGO_DESC';
$modversion['config'][3]['formtype'] = 'textbox';
$modversion['config'][3]['valuetype'] = 'text';
$modversion['config'][3]['default'] = "your_logo.gif";

$modversion['config'][4]['name'] = 'mrbs_company_more_info';
$modversion['config'][4]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY_MORE_INFO';
$modversion['config'][4]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY_MORE_INFO_DESC';
$modversion['config'][4]['formtype'] = 'textbox';
$modversion['config'][4]['valuetype'] = 'text';
$modversion['config'][4]['default'] = "You can put additional information here";

$modversion['config'][5]['name'] = 'mrbs_company_url';
$modversion['config'][5]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY_URL';
$modversion['config'][5]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_COMPANY_URL_DESC';
$modversion['config'][5]['formtype'] = 'textbox';
$modversion['config'][5]['valuetype'] = 'text';
$modversion['config'][5]['default'] = "http://www.your_organisation.com/";

$modversion['config'][6]['name'] = 'url_base';
$modversion['config'][6]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_URL_BASE';
$modversion['config'][6]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_URL_BASE_DESC';
$modversion['config'][6]['formtype'] = 'textbox';
$modversion['config'][6]['valuetype'] = 'text';
$modversion['config'][6]['default'] = XOOPS_URL."/modules/mrbs";

$modversion['config'][7]['name'] = 'showbooker';
$modversion['config'][7]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOWBOOKER";
$modversion['config'][7]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SHOWBOOKER_DESC';
$modversion['config'][7]['formtype'] = 'select';
$modversion['config'][7]['valuetype'] = 'text';
$modversion['config'][7]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOWBOOKER_UNAME"=>'uname',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOWBOOKER_NAME"=>'name',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOWBOOKER_BOTH"=>'both',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOWBOOKER_NONE"=>'none'
											);
$modversion['config'][7]['default'] = 'uname';

$modversion['config'][8]['name'] = 'showpastmonth';
$modversion['config'][8]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOWPASTMONTH";
$modversion['config'][8]['description'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOWPASTMONTH_DESC";
$modversion['config'][8]['formtype'] = 'yesno';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 0;

$modversion['config'][9]['name'] = 'enable_periods';
$modversion['config'][9]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_ENABLE_PERIODS";
$modversion['config'][9]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_ENABLE_PERIODS_DESC';
$modversion['config'][9]['formtype'] = 'select';
$modversion['config'][9]['valuetype'] = 'text';
$modversion['config'][9]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_ENABLE_PERIODS_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_ENABLE_PERIODS_FALSE"=>'FALSE'
											);
$modversion['config'][9]['default'] = 'FALSE';

$modversion['config'][10]['name'] = 'periods';
$modversion['config'][10]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_PERIODS';
$modversion['config'][10]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_PERIODS_DESC';
$modversion['config'][10]['formtype'] = 'textbox';
$modversion['config'][10]['valuetype'] = 'text';
$modversion['config'][10]['default'] = "P1,P2,P3";

$modversion['config'][11]['name'] = 'resolution';
$modversion['config'][11]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_RESOLUTION';
$modversion['config'][11]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_RESOLUTION_DESC';
$modversion['config'][11]['formtype'] = 'textbox';
$modversion['config'][11]['valuetype'] = 'int';
$modversion['config'][11]['default'] = "1800";

$modversion['config'][12]['name'] = 'default_duration';
$modversion['config'][12]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_DURATION';
$modversion['config'][12]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_DURATION_DESC';
$modversion['config'][12]['formtype'] = 'textbox';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = "3600";

$modversion['config'][13]['name'] = 'morningstarts';
$modversion['config'][13]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MORNINGSTARTS';
$modversion['config'][13]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MORNINGSTARTS_DESC';
$modversion['config'][13]['formtype'] = 'textbox';
$modversion['config'][13]['valuetype'] = 'int';
$modversion['config'][13]['default'] = "8";

$modversion['config'][14]['name'] = 'morningstarts_minutes';
$modversion['config'][14]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MORNINGSTARTS_MINUTES';
$modversion['config'][14]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MORNINGSTARTS_MINUTES_DESC';
$modversion['config'][14]['formtype'] = 'textbox';
$modversion['config'][14]['valuetype'] = 'int';
$modversion['config'][14]['default'] = "0";

$modversion['config'][15]['name'] = 'eveningends';
$modversion['config'][15]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_EVENINGENDS';
$modversion['config'][15]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_EVENINGENDS_DESC';
$modversion['config'][15]['formtype'] = 'textbox';
$modversion['config'][15]['valuetype'] = 'int';
$modversion['config'][15]['default'] = "18";

$modversion['config'][16]['name'] = 'eveningends_minutes';
$modversion['config'][16]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_EVENINGENDS_MINUTES';
$modversion['config'][16]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_EVENINGENDS_MINUTES_DESC';
$modversion['config'][16]['formtype'] = 'textbox';
$modversion['config'][16]['valuetype'] = 'int';
$modversion['config'][16]['default'] = "0";

$modversion['config'][17]['name'] = 'weekstarts';
$modversion['config'][17]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS";
$modversion['config'][17]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_WEEKSTARTS_DESC';
$modversion['config'][17]['formtype'] = 'select';
$modversion['config'][17]['valuetype'] = 'int';
$modversion['config'][17]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS_0"=>'0',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS_1"=>'1',
                                            "_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS_2"=>'2',
                                            "_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS_3"=>'3',
                                            "_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS_4"=>'4',
                                            "_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS_5"=>'5',
                                            "_MI_".$GLOBALS["MRBS_PREFIX"]."_WEEKSTARTS_6"=>'6',
											);
$modversion['config'][17]['default'] = '1';

$modversion['config'][18]['name'] = 'hidden_days';
$modversion['config'][18]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_HIDDEN_DAYS';
$modversion['config'][18]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_HIDDEN_DAYS_DESC';
$modversion['config'][18]['formtype'] = 'textbox';
$modversion['config'][18]['valuetype'] = 'text';
$modversion['config'][18]['default'] = "";

$modversion['config'][19]['name'] = 'dateformat';
$modversion['config'][19]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_DATEFORMAT";
$modversion['config'][19]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DATEFORMAT_DESC';
$modversion['config'][19]['formtype'] = 'select';
$modversion['config'][19]['valuetype'] = 'text';
$modversion['config'][19]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_DATEFORMAT_0"=>'0',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_DATEFORMAT_1"=>'1'
											);
$modversion['config'][19]['default'] = '1';

$modversion['config'][20]['name'] = 'twentyfourhour_format';
$modversion['config'][20]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_TWENTYFOURHOUR_FORMAT";
$modversion['config'][20]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_TWENTYFOURHOUR_FORMAT_DESC';
$modversion['config'][20]['formtype'] = 'select';
$modversion['config'][20]['valuetype'] = 'text';
$modversion['config'][20]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_TWENTYFOURHOUR_FORMAT_0"=>'0',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_TWENTYFOURHOUR_FORMAT_1"=>'1'
											);
$modversion['config'][20]['default'] = '1';

$modversion['config'][21]['name'] = 'max_rep_entrys';
$modversion['config'][21]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAX_REP_ENTRYS';
$modversion['config'][21]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAX_REP_ENTRYS_DESC';
$modversion['config'][21]['formtype'] = 'textbox';
$modversion['config'][21]['valuetype'] = 'int';
$modversion['config'][21]['default'] = "366";

$modversion['config'][22]['name'] = 'default_report_days';
$modversion['config'][22]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_REPORT_DAYS';
$modversion['config'][22]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_REPORT_DAYS_DESC';
$modversion['config'][22]['formtype'] = 'textbox';
$modversion['config'][22]['valuetype'] = 'int';
$modversion['config'][22]['default'] = "60";

$modversion['config'][23]['name'] = 'searchcount';
$modversion['config'][23]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SEARCHCOUNT';
$modversion['config'][23]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SEARCHCOUNT_DESC';
$modversion['config'][23]['formtype'] = 'textbox';
$modversion['config'][23]['valuetype'] = 'int';
$modversion['config'][23]['default'] = "20";

$modversion['config'][24]['name'] = 'refresh_rate';
$modversion['config'][24]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_REFRESH_RATE';
$modversion['config'][24]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_REFRESH_RATE_DESC';
$modversion['config'][24]['formtype'] = 'textbox';
$modversion['config'][24]['valuetype'] = 'int';
$modversion['config'][24]['default'] = "0";

$modversion['config'][25]['name'] = 'simple_trailer';
$modversion['config'][25]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_SIMPLE_TRAILER";
$modversion['config'][25]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SIMPLE_TRAILER_DESC';
$modversion['config'][25]['formtype'] = 'select';
$modversion['config'][25]['valuetype'] = 'text';
$modversion['config'][25]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SIMPLE_TRAILER_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SIMPLE_TRAILER_FALSE"=>'FALSE'
											);
$modversion['config'][25]['default'] = 'TRUE';

$modversion['config'][26]['name'] = 'area_list_format';
$modversion['config'][26]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_AREA_LIST_FORMAT";
$modversion['config'][26]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_AREA_LIST_FORMAT_DESC';
$modversion['config'][26]['formtype'] = 'select';
$modversion['config'][26]['valuetype'] = 'text';
$modversion['config'][26]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_AREA_LIST_FORMAT_LIST"=>'list',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_AREA_LIST_FORMAT_SELECT"=>'select'
											);
$modversion['config'][26]['default'] = 'select';

$modversion['config'][27]['name'] = 'monthly_view_entries_det'; //monthly_view_entries_details
$modversion['config'][27]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MONTHLY_VIEW_ENTRIES_DETAILS";
$modversion['config'][27]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MONTHLY_VIEW_ENTRIES_DETAILS_DESC';
$modversion['config'][27]['formtype'] = 'select';
$modversion['config'][27]['valuetype'] = 'text';
$modversion['config'][27]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MONTHLY_VIEW_ENTRIES_DETAILS_D"=>'description',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MONTHLY_VIEW_ENTRIES_DETAILS_S"=>'slot',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MONTHLY_VIEW_ENTRIES_DETAILS_B"=>'both'
											);
$modversion['config'][27]['default'] = 'both';

$modversion['config'][28]['name'] = 'view_week_number';
$modversion['config'][28]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_VIEW_WEEK_NUMBER";
$modversion['config'][28]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_VIEW_WEEK_NUMBER_DESC';
$modversion['config'][28]['formtype'] = 'select';
$modversion['config'][28]['valuetype'] = 'text';
$modversion['config'][28]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_VIEW_WEEK_NUMBER_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_VIEW_WEEK_NUMBER_FALSE"=>'FALSE'
											);
$modversion['config'][28]['default'] = 'FALSE';

$modversion['config'][29]['name'] = 'times_right_side';
$modversion['config'][29]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_TIMES_RIGHT_SIDE";
$modversion['config'][29]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_TIMES_RIGHT_SIDE_DESC';
$modversion['config'][29]['formtype'] = 'select';
$modversion['config'][29]['valuetype'] = 'text';
$modversion['config'][29]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_TIMES_RIGHT_SIDE_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_TIMES_RIGHT_SIDE_FALSE"=>'FALSE'
											);
$modversion['config'][29]['default'] = 'FALSE';

$modversion['config'][30]['name'] = 'javascript_cursor';
$modversion['config'][30]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_JAVASCRIPT_CURSOR";
$modversion['config'][30]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_JAVASCRIPT_CURSOR_DESC';
$modversion['config'][30]['formtype'] = 'select';
$modversion['config'][30]['valuetype'] = 'text';
$modversion['config'][30]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_JAVASCRIPT_CURSOR_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_JAVASCRIPT_CURSOR_FALSE"=>'FALSE'
											);
$modversion['config'][30]['default'] = 'TRUE';

$modversion['config'][31]['name'] = 'highlight_method';
$modversion['config'][31]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_HIGHLIGHT_METHOD";
$modversion['config'][31]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_HIGHLIGHT_METHOD_DESC';
$modversion['config'][31]['formtype'] = 'select';
$modversion['config'][31]['valuetype'] = 'text';
$modversion['config'][31]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_HIGHLIGHT_METHOD_HYBRID"=>'hybrid',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_HIGHLIGHT_METHOD_CLASS"=>'class',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_HIGHLIGHT_METHOD_BGCOLOR"=>'bgcolor'
											);
$modversion['config'][32]['default'] = 'hybrid';

$modversion['config'][32]['name'] = 'show_plus_link';
$modversion['config'][32]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOW_PLUS_LINK";
$modversion['config'][32]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SHOW_PLUS_LINK_DESC';
$modversion['config'][32]['formtype'] = 'select';
$modversion['config'][32]['valuetype'] = 'text';
$modversion['config'][32]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOW_PLUS_LINK_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SHOW_PLUS_LINK_FALSE"=>'FALSE'
											);
$modversion['config'][32]['default'] = 'FALSE';

$modversion['config'][33]['name'] = 'default_view';
$modversion['config'][33]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_DEFAULT_VIEW";
$modversion['config'][33]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_VIEW_DESC';
$modversion['config'][33]['formtype'] = 'select';
$modversion['config'][33]['valuetype'] = 'text';
$modversion['config'][33]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_DEFAULT_VIEW_DAY"=>'day',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_DEFAULT_VIEW_WEEK"=>'week',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_DEFAULT_VIEW_MONTH"=>'month'
											);
$modversion['config'][33]['default'] = 'week';

$modversion['config'][34]['name'] = 'default_room';
$modversion['config'][34]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_ROOM';
$modversion['config'][34]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_ROOM_DESC';
$modversion['config'][34]['formtype'] = 'textbox';
$modversion['config'][34]['valuetype'] = 'int';
$modversion['config'][34]['default'] = "0";

$modversion['config'][35]['name'] = 'month_cell_scrolling';
$modversion['config'][35]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MONTH_CELL_SCROLLING';
$modversion['config'][35]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MONTH_CELL_SCROLLING_DESC';
$modversion['config'][35]['formtype'] = 'select';
$modversion['config'][35]['valuetype'] = 'text';
$modversion['config'][35]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MONTH_CELL_SCROLLING_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MONTH_CELL_SCROLLING_FALSE"=>'FALSE'
											);
$modversion['config'][35]['default'] = 'FALSE';

$modversion['config'][36]['name'] = 'timezone';
$modversion['config'][36]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_TIMEZONE";
$modversion['config'][36]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_TIMEZONE_DESC';
$modversion['config'][36]['formtype'] = 'textbox';
$modversion['config'][36]['valuetype'] = 'text';
$modversion['config'][36]['default'] = '';


$modversion['config'][37]['name'] = 'session';
$modversion['config'][37]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_SESSION";
$modversion['config'][37]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SESSION_DESC';
$modversion['config'][37]['formtype'] = 'select';
$modversion['config'][37]['valuetype'] = 'text';
$modversion['config'][37]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SESSION_PHP"=>'php',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SESSION_HTTP"=>'http'
											);
$modversion['config'][37]['default'] = 'php';

$modversion['config'][38]['name'] = 'mail_admin_on_bookings';
$modversion['config'][38]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ON_BOOKINGS";
$modversion['config'][38]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_ADMIN_ON_BOOKINGS_DESC';
$modversion['config'][38]['formtype'] = 'select';
$modversion['config'][38]['valuetype'] = 'text';
$modversion['config'][38]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ON_BOOKINGS_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ON_BOOKINGS_FALSE"=>'FALSE'
											);
$modversion['config'][38]['default'] = 'FALSE';

$modversion['config'][39]['name'] = 'mail_area_admin_on_book';
$modversion['config'][39]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_AREA_ADMIN_ON_BOOKINGS";
$modversion['config'][39]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_AREA_ADMIN_ON_BOOKINGS_DESC';
$modversion['config'][39]['formtype'] = 'select';
$modversion['config'][39]['valuetype'] = 'text';
$modversion['config'][39]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_AREA_ADMIN_ON_BOOKINGS_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_AREA_ADMIN_ON_BOOKINGS_FALSE"=>'FALSE'
											);
$modversion['config'][39]['default'] = 'FALSE';

$modversion['config'][40]['name'] = 'mail_room_admin_on_book';
$modversion['config'][40]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ROOM_ADMIN_ON_BOOKINGS";
$modversion['config'][40]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_ROOM_ADMIN_ON_BOOKINGS_DESC';
$modversion['config'][40]['formtype'] = 'select';
$modversion['config'][40]['valuetype'] = 'text';
$modversion['config'][40]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ROOM_ADMIN_ON_BOOKINGS_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ROOM_ADMIN_ON_BOOKINGS_FALSE"=>'FALSE'
											);
$modversion['config'][40]['default'] = 'FALSE';

$modversion['config'][41]['name'] = 'mail_admin_on_delete';
$modversion['config'][41]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ON_DELETE";
$modversion['config'][41]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_ADMIN_ON_DELETE_DESC';
$modversion['config'][41]['formtype'] = 'select';
$modversion['config'][41]['valuetype'] = 'text';
$modversion['config'][41]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ON_DELETE_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ON_DELETE_FALSE"=>'FALSE'
											);
$modversion['config'][41]['default'] = 'FALSE';

$modversion['config'][42]['name'] = 'mail_admin_all';
$modversion['config'][42]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ALL";
$modversion['config'][42]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_ADMIN_ALL_DESC';
$modversion['config'][42]['formtype'] = 'select';
$modversion['config'][42]['valuetype'] = 'text';
$modversion['config'][42]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ALL_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_ALL_FALSE"=>'FALSE'
											);
$modversion['config'][42]['default'] = 'FALSE';

$modversion['config'][43]['name'] = 'mail_details';
$modversion['config'][43]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_DETAILS";
$modversion['config'][43]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_DETAILS_DESC';
$modversion['config'][43]['formtype'] = 'select';
$modversion['config'][43]['valuetype'] = 'text';
$modversion['config'][43]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_DETAILS_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_DETAILS_FALSE"=>'FALSE'
											);
$modversion['config'][43]['default'] = 'FALSE';

$modversion['config'][44]['name'] = 'mail_booker';
$modversion['config'][44]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_BOOKER";
$modversion['config'][44]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_BOOKER_DESC';
$modversion['config'][44]['formtype'] = 'select';
$modversion['config'][44]['valuetype'] = 'text';
$modversion['config'][44]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_BOOKER_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_BOOKER_FALSE"=>'FALSE'
											);
$modversion['config'][44]['default'] = 'FALSE';

$modversion['config'][45]['name'] = 'mail_admin_backend';
$modversion['config'][45]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_BACKEND";
$modversion['config'][45]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_ADMIN_BACKEND_DESC';
$modversion['config'][45]['formtype'] = 'select';
$modversion['config'][45]['valuetype'] = 'text';
$modversion['config'][45]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_BACKEND_MAIL"=>'mail',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_BACKEND_SMTP"=>'smtp',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_MAIL_ADMIN_BACKEND_SENDMAIL"=>'sendmail'
											);
$modversion['config'][45]['default'] = 'mail';

$modversion['config'][46]['name'] = 'sendmail_path';
$modversion['config'][46]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SENDMAIL_PATH';
$modversion['config'][46]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SENDMAIL_PATH_DESC';
$modversion['config'][46]['formtype'] = 'textbox';
$modversion['config'][46]['valuetype'] = 'text';
$modversion['config'][46]['default'] = "/usr/bin/sendmail";

$modversion['config'][47]['name'] = 'sendmail_args';
$modversion['config'][47]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SENDMAIL_ARGS';
$modversion['config'][47]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SENDMAIL_ARGS_DESC';
$modversion['config'][47]['formtype'] = 'textbox';
$modversion['config'][47]['valuetype'] = 'text';
$modversion['config'][47]['default'] = "-t -i";

$modversion['config'][48]['name'] = 'smtp_host';
$modversion['config'][48]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_HOST';
$modversion['config'][48]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_HOST_DESC';
$modversion['config'][48]['formtype'] = 'textbox';
$modversion['config'][48]['valuetype'] = 'text';
$modversion['config'][48]['default'] = "smtp.domain.com";

$modversion['config'][49]['name'] = 'smtp_port';
$modversion['config'][49]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_PORT';
$modversion['config'][49]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_PORT_DESC';
$modversion['config'][49]['formtype'] = 'textbox';
$modversion['config'][49]['valuetype'] = 'int';
$modversion['config'][49]['default'] = "25";

$modversion['config'][50]['name'] = 'smtp_auth';
$modversion['config'][50]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_SMTP_AUTH";
$modversion['config'][50]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_AUTH_DESC';
$modversion['config'][50]['formtype'] = 'select';
$modversion['config'][50]['valuetype'] = 'text';
$modversion['config'][50]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SMTP_AUTH_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_SMTP_AUTH_FALSE"=>'FALSE'
											);
$modversion['config'][50]['default'] = 'FALSE';

$modversion['config'][51]['name'] = 'smtp_username';
$modversion['config'][51]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_USERNAME';
$modversion['config'][51]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_USERNAME_DESC';
$modversion['config'][51]['formtype'] = 'textbox';
$modversion['config'][51]['valuetype'] = 'text';
$modversion['config'][51]['default'] = "smtp username";

$modversion['config'][52]['name'] = 'smtp_password';
$modversion['config'][52]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_PASSWORD';
$modversion['config'][52]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_SMTP_PASSWORD_DESC';
$modversion['config'][52]['formtype'] = 'textbox';
$modversion['config'][52]['valuetype'] = 'text';
$modversion['config'][52]['default'] = "smtp password";

$modversion['config'][53]['name'] = 'mail_admin_lang';
$modversion['config'][53]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_ADMIN_LANG';
$modversion['config'][53]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_ADMIN_LANG_DESC';
//$modversion['config'][53]['formtype'] = 'textbox';
$modversion['config'][53]['formtype'] = 'select';
$modversion['config'][53]['valuetype'] = 'text';
// MRBS Mail Admin Language
$folders = array('');
// Set the root path to the faq folder
$templatedir = XOOPS_ROOT_PATH . '/modules/' . $modversion['dirname'].'/';
$files = array();
foreach ( $folders as $folder )
{
 $dir = opendir($templatedir.$folder);
 while (( $file = readdir($dir)) !== false )
 {
  if ( !preg_match("/^[.]{1,2}$/", $file) )
  {
   if( preg_match("/lang./", $file) && !preg_match("/.inc/", $file) )
   {
     if (strtolower($file) != 'cvs' && !is_dir($file))
     {   
     $files[] = $file;
     }
    }
   }
  }
closedir($dir);
}
sort($files);
foreach ($files as $k => $v) {
    $mail_admin_lang[$v] = preg_replace('/lang./','',$v);//create a new associative array


}//end foreach
$modversion['config'][53]['options'] = $mail_admin_lang;
$modversion['config'][53]['default'] = "en";

$modversion['config'][54]['name'] = 'mail_from';
$modversion['config'][54]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_FROM';
$modversion['config'][54]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_FROM_DESC';
$modversion['config'][54]['formtype'] = 'textbox';
$modversion['config'][54]['valuetype'] = 'text';
$modversion['config'][54]['default'] = "";

$modversion['config'][55]['name'] = 'mail_recipients';
$modversion['config'][55]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_RECIPIENTS';
$modversion['config'][55]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_RECIPIENTS_DESC';
$modversion['config'][55]['formtype'] = 'textbox';
$modversion['config'][55]['valuetype'] = 'text';
$modversion['config'][55]['default'] = "";

$modversion['config'][56]['name'] = 'mail_cc';
$modversion['config'][56]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_CC';
$modversion['config'][56]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_CC_DESC';
$modversion['config'][56]['formtype'] = 'textbox';
$modversion['config'][56]['valuetype'] = 'text';
$modversion['config'][56]['default'] = "";

$modversion['config'][57]['name'] = 'unicode_encoding';
$modversion['config'][57]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_UNICODE_ENCODING";
$modversion['config'][57]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_UNICODE_ENCODING_DESC';
$modversion['config'][57]['formtype'] = 'select';
$modversion['config'][57]['valuetype'] = 'text';
$modversion['config'][57]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_UNICODE_ENCODING_0"=>'0',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_UNICODE_ENCODING_1"=>'1'
											);
$modversion['config'][57]['default'] = '1';

$modversion['config'][58]['name'] = 'mail_charset';
$modversion['config'][58]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_CHARSET';
$modversion['config'][58]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_MAIL_CHARSET_DESC';
$modversion['config'][58]['formtype'] = 'textbox';
$modversion['config'][58]['valuetype'] = 'text';
$modversion['config'][58]['default'] = "";

$modversion['config'][59]['name'] = 'default_language_tokens';
$modversion['config'][59]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_LANGUAGE_TOKENS';
$modversion['config'][59]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DEFAULT_LANGUAGE_TOKENS_DESC';
//$modversion['config'][59]['formtype'] = 'textbox';
$modversion['config'][59]['formtype'] = 'select';
$modversion['config'][59]['valuetype'] = 'text';

// MRBS Mail Admin Language
$folders = array('');
// Set the root path to the faq folder
$templatedir = XOOPS_ROOT_PATH . '/modules/' . $modversion['dirname'].'/';
$files = array();
foreach ( $folders as $folder )
{
 $dir = opendir($templatedir.$folder);
 while (( $file = readdir($dir)) !== false )
 {
  if ( !preg_match("/^[.]{1,2}$/", $file) )
  {
   if( preg_match("/lang./", $file) && !preg_match("/.inc/", $file) )
   {
     if (strtolower($file) != 'cvs' && !is_dir($file))
     {   
     $files[] = $file;
     }
    }
   }
  }
closedir($dir);
}
sort($files);
foreach ($files as $k => $v) {
    $default_language_tokens[$v] = preg_replace('/lang./','',$v);//create a new associative array

}//end foreach
$modversion['config'][59]['options'] = $default_language_tokens;
$modversion['config'][59]['default'] = "en";

$modversion['config'][60]['name'] = 'disable_automatic_lang';
$modversion['config'][60]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_DISABLE_AUTOMATIC_LANGUAGE";
$modversion['config'][60]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_DISABLE_AUTOMATIC_LANGUAGE_DESC';
$modversion['config'][60]['formtype'] = 'select';
$modversion['config'][60]['valuetype'] = 'text';
$modversion['config'][60]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_DISABLE_AUTOMATIC_LANGUAGE_0"=>'0',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_DISABLE_AUTOMATIC_LANGUAGE_1"=>'1'
											);
$modversion['config'][60]['default'] = '0';

$modversion['config'][61]['name'] = 'faqfilelang';
$modversion['config'][61]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_FAQFILELANG';
$modversion['config'][61]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_FAQFILELANG_DESC';
//$modversion['config'][61]['formtype'] = 'textbox';
$modversion['config'][61]['formtype'] = 'select';
$modversion['config'][61]['valuetype'] = 'text';
// MRBS FAQ
$folders = array('');
// Set the root path to the faq folder
$templatedir = XOOPS_ROOT_PATH . '/modules/' . $modversion['dirname'].'/';
$files = array();
foreach ( $folders as $folder )
{
 $dir = opendir($templatedir.$folder);
 while (( $file = readdir($dir)) !== false )
 {
  if ( !preg_match("/^[.]{1,2}$/", $file) )
  {
   if( preg_match("/site_faq/", $file) )
   {
     if (strtolower($file) != 'cvs' && !is_dir($file))
     {   
     $files[] = $file;
     }
    }
   }
  }
closedir($dir);
}
sort($files);
foreach ($files as $k => $v) {
    $faq[$v] = preg_replace('/site_faq/','',preg_replace('/.html/','',$v));//create a new associative array

}//end foreach
$modversion['config'][61]['options'] = $faq;
$modversion['config'][61]['default'] = "_en";

$modversion['config'][62]['name'] = 'theme';
$modversion['config'][62]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_THEME';
$modversion['config'][62]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_THEME_DESC';
$modversion['config'][62]['formtype'] = 'select';
//$modversion['config'][62]['formtype'] = 'textbox';
$modversion['config'][62]['valuetype'] = 'text';
// MRBS Templates
$folders = array('');
// Set the root path to the template folder
$templatedir = XOOPS_ROOT_PATH . '/modules/' . $modversion['dirname'] . '/Themes/';
$files = array();
foreach ( $folders as $folder )
{
 $dir = opendir($templatedir.$folder);
 while (( $file = readdir($dir)) !== false )
 {
  if ( !preg_match("/^[.]{1,2}$/", $file) )
  {
   if( preg_match("/inc/", $file) )
   {
     if (strtolower($file) != 'cvs' && !is_dir($file))
     {   
     $files[] = $file;
     }
    }
   }
  }
closedir($dir);
}
sort($files);
foreach ($files as $k => $v) {
    $themes[$v] = $v;//create a new associative array
}//end foreach
$modversion['config'][62]['options'] = $themes;
$modversion['config'][62]['default'] = "default.inc";

$modversion['config'][63]['name'] = 'entry_types';
$modversion['config'][63]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_ENTRY_TYPES';
$modversion['config'][63]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_ENTRY_TYPES_DESC';
$modversion['config'][63]['formtype'] = 'textbox';
$modversion['config'][63]['valuetype'] = 'text';
$modversion['config'][63]['default'] = "";

$modversion['config'][64]['name'] = 'use_limit_time_booking';
$modversion['config'][64]['title'] = "_MI_".$GLOBALS["MRBS_PREFIX"]."_USE_LIMIT_TIME_BOOKING";
$modversion['config'][64]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_USE_LIMIT_TIME_BOOKING_DESC';
$modversion['config'][64]['formtype'] = 'select';
$modversion['config'][64]['valuetype'] = 'text';
$modversion['config'][64]['options'] = array(
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_USE_LIMIT_TIME_BOOKING_TRUE"=>'TRUE',
											"_MI_".$GLOBALS["MRBS_PREFIX"]."_USE_LIMIT_TIME_BOOKING_FALSE"=>'FALSE'
											);
$modversion['config'][64]['default'] = 'FALSE';

$modversion['config'][65]['name'] = 'time_booking';
$modversion['config'][65]['title'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_TIME_BOOKING';
$modversion['config'][65]['description'] = '_MI_'.$GLOBALS["MRBS_PREFIX"].'_TIME_BOOKING_DESC';
$modversion['config'][65]['formtype'] = 'textbox';
$modversion['config'][65]['valuetype'] = 'text';
$modversion['config'][65]['default'] = "90";
?>